name: "Publish museum server"

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and push
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          dockerfile: server/Dockerfile
          directory: server
          registry: docker.io
          image: jatinkatyal13/museum
          enableBuildKit: true
          multiPlatform: true
          platform: linux/amd64,linux/arm64
          tags: ${{ github.sha }}, latest
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
